name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check for secrets leak on the repo
      run: |
          git clone https://github.com/awslabs/git-secrets.git target
          cd target
          sudo make install
          echo "Git-secrets installation completed"
          git secrets --register-aws --global
          echo "Added aws secret templates"
          git secrets --scan -r ../
          echo "Repository scan completed"
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore RecommendationTools/RecommendationValidator/RecommendationValidator.csproj
    - name: Validate
      run: for FILE in ./recommendation/*.recommendation.json ; do dotnet run --project RecommendationTools/RecommendationValidator/RecommendationValidator.csproj --path $FILE; done
